config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :user_types

   root 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base
   belongs_to :user_type
  validates :user_type_id, :nombre, :apellido, :email, presence: true
end

app/models/user_type.rb
class UserType < ActiveRecord::Base
  has_many :users
  validates :nombre, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/user_types_controller.rb
class UserTypesController < ApplicationController
  before_action :set_user_type, only: [:show, :edit, :update, :destroy]

  # GET /user_types
  # GET /user_types.json
  def index
    @user_types = UserType.all
  end

  # GET /user_types/1
  # GET /user_types/1.json
  def show
  end

  # GET /user_types/new
  def new
    @user_type = UserType.new
  end

  # GET /user_types/1/edit
  def edit
  end

  # POST /user_types
  # POST /user_types.json
  def create
    @user_type = UserType.new(user_type_params)

    respond_to do |format|
      if @user_type.save
        format.html { redirect_to @user_type, notice: 'User type was successfully created.' }
        format.json { render :show, status: :created, location: @user_type }
      else
        format.html { render :new }
        format.json { render json: @user_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_types/1
  # PATCH/PUT /user_types/1.json
  def update
    respond_to do |format|
      if @user_type.update(user_type_params)
        format.html { redirect_to @user_type, notice: 'User type was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_type }
      else
        format.html { render :edit }
        format.json { render json: @user_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_types/1
  # DELETE /user_types/1.json
  def destroy
    @user_type.destroy
    respond_to do |format|
      format.html { redirect_to user_types_url, notice: 'User type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_type
      @user_type = UserType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_type_params
      params.require(:user_type).permit(:nombre, :description, :deleted)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy,:active]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def active
    status = params[:status]
    real_status = (status == 'true' ? true : false)
    @station.enabled = real_status


    respond_to do |format|
      if @station.save
        format.json{head :no_content, status: :ok}
      else
        format.json{head :no_content, status: :unprocessable_entity}
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user_type_id, :nombre, :apellido, :email, :deleted)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_types_helper.rb
module UserTypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HatosGanaderos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/user_types/_form.html.erb
<%= form_for(@user_type) do |f| %>
  <% if @user_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_type.errors.count, "error") %> prohibited this user_type from being saved:</h2>

      <ul>
      <% @user_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :deleted %><br>
    <%= f.check_box :deleted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_types/edit.html.erb
<h1>Editing User Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_type %> |
<%= link_to 'Back', user_types_path %>

app/views/user_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Types</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Description</th>
      <th>Deleted</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_types.each do |user_type| %>
      <tr>
        <td><%= user_type.nombre %></td>
        <td><%= user_type.description %></td>
        <td><%= user_type.deleted %></td>
        <td><%= link_to 'Show', user_type %></td>
        <td><%= link_to 'Edit', edit_user_type_path(user_type) %></td>
        <td><%= link_to 'Destroy', user_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User type', new_user_type_path %>
<%= link_to 'New user', new_user_path %>

app/views/user_types/new.html.erb
<h1>New User Type</h1>

<%= render 'form' %>

<%= link_to 'Back', user_types_path %>

app/views/user_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @user_type.nombre %>
</p>

<p>
  <strong>Description:</strong>
  <%= @user_type.description %>
</p>

<p>
  <strong>Deleted:</strong>
  <%= @user_type.deleted %>
</p>

<%= link_to 'Edit', edit_user_type_path(@user_type) %> |
<%= link_to 'Back', user_types_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_type_id %><br>
    <%= f.text_field :user_type_id  %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellido %><br>
    <%= f.text_field :apellido %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :deleted %><br>
    <%= f.check_box :deleted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<%= link_to 'Cancel', users_path %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>User type</th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Email</th>
      <th>Deleted</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.user_type_id %></td>
        <td><%= user.nombre %></td>
        <td><%= user.apellido %></td>
        <td><%= user.email %></td>
        <td><%= check_box_tag 'user_active', user.id, user.deleted, class: 'checkbox_active' %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, id: "new_link", remote: true %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>');

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User type:</strong>
  <%= @user.user_type_id %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @user.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @user.apellido %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Deleted:</strong>
  <%= @user.deleted %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>